#!/Users/brian/bin/perl
use v5.10;

use IO::Interactive qw(is_interactive);

my $dir    = $ARGV[0] // "$ENV{HOME}/Library/CloudStorage/Dropbox";
my $avenza = $ARGV[1] // "$ENV{HOME}/Library/CloudStorage/Dropbox/Avenza";

chdir $dir or die "$0: Could not change to <$dir>: $!\n";

my @files = glob( "*.gpx" );
say join "\n\t", "Found files to split:", @files;

exit() unless @files;

foreach my $file ( @files ) {
	system 'gpx_splitter', $file;
	}

# The files may have changed, so look again
@files = glob( "*.gpx" );
say join "\n\t", "Found files to rename:", @files;

foreach my $file ( @files ) {
	system 'gpx_renamer', $file;
	}

@files = glob( "*.gpx *.gpx.bak" );
foreach my $file ( @files ) {
	system 'mv', $file, $avenza;
	}

exit();

=encoding utf8

=head1 NAME

gpx_watcher - watch for new .gpx files and process them

=head1 SYNOPSIS

I can run this from the command line:

	# DROPBOX_DIR default is $HOME/Library/CloudStorage/Dropbox
	# DEST_DIR default is $HOME/Library/CloudStorage/Dropbox/Avenza
	$ gpx_watcher [DROPBOX_DIR] [DEST_DIR]

I use this from cron:

	*/5 * * * * ${HOME}/bin/gpx_tools/gpx_watcher

=head1 DESCRIPTION

This program watches my Dropbox directory for F<.gpx> files. If it finds
any, it runs F<gpx_splitter> and F<gpx_renamer> on those files. Those tools
are part of this repo.

=head1 SOURCE

The source is at L<https://github.com/briandfoy/brians_gpx_tools>.

The repos are also stored at other services as noted in the README.

=head1 LICENSE

This code is available under the Artistic License 2.0. A LICENSE file
should have come with the repo, but you can also see the license at
L<https://opensource.org/license/artistic-2-0/>

=head1 AUTHOR

brian d foy, briandfoy@pobox.com

=cut
