#!/Users/brian/bin/perl
use v5.10;

use IO::Interactive qw(is_interactive);

use Mojo::DOM;
use Mojo::File;
use Mojo::Util qw(dumper);

my $file = Mojo::File->new($ARGV[0]);

my $basename_orig = $file->basename;
my $dir = $file->dirname;
chdir $dir;

my $contents = $file->slurp;

my $dom = Mojo::DOM->new( $contents )->xml(1);
my $date = $dom->at( 'gpx trk trkseg trkpt time' )->text;
$date =~ s/T.*//;
$date =~ s/-//g;
#say STDERR "Date is <$date>" if is_interactive();


my $basename_new = "$date - unknown.gpx";
if( $basename_orig eq $basename_new ) {
	say STDERR "original and new names are the same: skipping"  if is_interactive();
	exit(65);
	}

while( -e $basename_new ) {
	state $n = 0;
	$n++;
	$basename_new =~ s/(?=\.gpx$)/ - $n/;
	}

say STDERR "Renaming to <$basename_orig> => <$basename_new>" if is_interactive();

rename $basename_orig => $basename_new;
